//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace jobportal
{
    using System;
    using System.Collections.Generic;
    
    public partial class jobdetail
    {
        public System.Guid PK_JobID { get; set; }
        public Nullable<System.Guid> FK_CategoryID { get; set; }
        public Nullable<System.Guid> FK_EmployementID { get; set; }
        public Nullable<System.Guid> FK_CompanyID { get; set; }
        public Nullable<System.Guid> FK_CountryID { get; set; }
        public Nullable<System.Guid> FK_StateID { get; set; }
        public Nullable<System.Guid> FK_ExpericeID { get; set; }
        public string jobdesgination { get; set; }
        public Nullable<int> minsalary { get; set; }
        public Nullable<int> maxsalary { get; set; }
        public Nullable<System.DateTime> jobposteddate { get; set; }
        public Nullable<bool> isactive { get; set; }
        public string image { get; set; }
    
        public virtual lkpcompany lkpcompany { get; set; }
        public virtual lkpcategory lkpcategory { get; set; }
        public virtual lkpemployement_type lkpemployement_type { get; set; }
        public virtual lkpexperiencetype lkpexperiencetype { get; set; }
        public virtual lkpcountry lkpcountry { get; set; }
        public virtual lkpState lkpState { get; set; }
    }
}
