//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace jobportal
{
    using System;
    using System.Collections.Generic;
    
    public partial class languageproficiency
    {
        public System.Guid PK_LanguageProficiencyID { get; set; }
        public Nullable<System.Guid> FK_MemberID { get; set; }
        public string LanguageName { get; set; }
        public Nullable<decimal> Rating { get; set; }
    
        public virtual careerdetail careerdetail { get; set; }
    }
}
