//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace jobportal
{
    using System;
    using System.Collections.Generic;
    
    public partial class personaldetail
    {
        public System.Guid PK_MemberUserID { get; set; }
        public Nullable<System.Guid> FK_MemberID { get; set; }
        public string LastName { get; set; }
        public string FatherName { get; set; }
        public string MotherName { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string BirthPlace { get; set; }
        public string Nationality { get; set; }
        public string Sex { get; set; }
        public string Address { get; set; }
        public string email { get; set; }
        public string PhoneNumber { get; set; }
    
        public virtual careerdetail careerdetail { get; set; }
    }
}
