//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace jobportal
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SankeerthiEntities : DbContext
    {
        public SankeerthiEntities()
            : base("name=SankeerthiEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<careerdetail> careerdetails { get; set; }
        public virtual DbSet<educationdetail> educationdetails { get; set; }
        public virtual DbSet<jobdetail> jobdetails { get; set; }
        public virtual DbSet<languageproficiency> languageproficiencies { get; set; }
        public virtual DbSet<lkpcategory> lkpcategories { get; set; }
        public virtual DbSet<lkpcompany> lkpcompanies { get; set; }
        public virtual DbSet<lkpcountry> lkpcountries { get; set; }
        public virtual DbSet<lkpemployement_type> lkpemployement_type { get; set; }
        public virtual DbSet<lkpexperiencetype> lkpexperiencetypes { get; set; }
        public virtual DbSet<lkpState> lkpStates { get; set; }
        public virtual DbSet<personaldetail> personaldetails { get; set; }
        public virtual DbSet<usertable> usertables { get; set; }
        public virtual DbSet<workhistory> workhistories { get; set; }
    }
}
