//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace jobportal
{
    using System;
    using System.Collections.Generic;
    
    public partial class workhistory
    {
        public System.Guid PK_WorkHistoryID { get; set; }
        public Nullable<System.Guid> FK_MemberID { get; set; }
        public string CompanyName { get; set; }
        public string Desgination { get; set; }
        public Nullable<System.DateTime> TimePeriod_From { get; set; }
        public Nullable<System.DateTime> TimePeriod_To { get; set; }
        public string JobDescription { get; set; }
    
        public virtual careerdetail careerdetail { get; set; }
    }
}
